--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    id bigint NOT NULL,
    create_date_time timestamp(6) without time zone,
    updated_date_time timestamp(6) without time zone,
    uuid uuid,
    c_description character varying(255),
    c_name character varying(255),
    status boolean
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id bigint NOT NULL,
    create_date_time timestamp(6) without time zone,
    updated_date_time timestamp(6) without time zone,
    uuid uuid,
    p_description character varying(255),
    p_name character varying(255),
    price double precision,
    status boolean,
    category_id bigint,
    sub_category_id bigint
);


ALTER TABLE public.product OWNER TO postgres;

--
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sub_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sub_category (
    id bigint NOT NULL,
    create_date_time timestamp(6) without time zone,
    updated_date_time timestamp(6) without time zone,
    uuid uuid,
    sc_description character varying(255),
    sc_name character varying(255),
    category_id bigint
);


ALTER TABLE public.sub_category OWNER TO postgres;

--
-- Name: sub_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sub_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sub_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (id, create_date_time, updated_date_time, uuid, c_description, c_name, status) FROM stdin;
1	2026-07-24 01:16:49.691365	2026-07-24 01:16:49.691365	a2e6bf13-91f4-4907-87c0-927eabf5d605	\N	Cosmetics	t
2	2026-07-24 01:17:26.368688	2026-07-24 01:17:26.368688	e5580744-de45-4af7-874c-eda5ff5b6959	\N	Electronics	t
\.


--
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product (id, create_date_time, updated_date_time, uuid, p_description, p_name, price, status, category_id, sub_category_id) FROM stdin;
1	2026-07-24 01:30:03.183632	2026-07-24 01:30:03.183632	55d11a39-4187-4742-af48-4e1b55acb2ab	\N	HiMont Kids Instant Print Camera	1000	t	2	2
2	2026-07-24 01:30:59.865776	2026-07-24 01:30:59.865776	f5b92eca-cab8-4296-817c-89b8a2db1587	\N	Toy2	1500	t	2	2
3	2026-07-24 01:31:08.64876	2026-07-24 01:31:08.64876	c5325cab-91e5-4d87-8739-47debfccdb22	\N	Toy3	1500	t	2	2
4	2026-07-24 01:31:17.365665	2026-07-24 01:31:17.365665	6f35a1cb-268f-413a-beed-fe9e1ffb4866	\N	Toy4	2500	t	2	2
5	2026-07-24 01:31:25.717126	2026-07-24 01:31:25.717126	7467ed6b-b9eb-451a-9226-9b84b582eb87	\N	Toy5	2800	t	2	2
6	2026-07-24 01:31:33.44968	2026-07-24 01:31:33.44968	9b234817-7d0a-4578-a0dc-3858288a03fa	\N	Toy7	2800	t	2	2
7	2026-07-24 01:31:44.181837	2026-07-24 01:31:44.181837	5908b4db-25d0-4379-ae4d-3fe08e4773d3	\N	Toy8	3000	t	2	2
8	2026-07-24 01:31:52.081464	2026-07-24 01:31:52.081464	55555f33-77b3-43da-81b6-c043ab48757b	\N	Toy9	3200	t	2	2
9	2026-07-24 01:31:59.565438	2026-07-24 01:31:59.565438	4d34a026-2363-454a-9be8-789d1c9fbe7e	\N	Toy10	3500	t	2	2
10	2026-07-24 01:32:05.948807	2026-07-24 01:32:05.948807	2b0aae0d-a721-4355-835f-3e1db8dcc188	\N	Toy11	3800	t	2	2
11	2026-07-24 01:32:13.531183	2026-07-24 01:32:13.531183	a01ab750-edd1-4ec6-962e-d50add316215	\N	Toy12	9000	t	2	2
12	2026-07-24 01:32:35.07883	2026-07-24 01:32:35.07883	811d97e2-55cf-4b15-a882-8d007f4878ea	\N	Toy13	9300	t	2	2
13	2026-07-24 01:32:42.664391	2026-07-24 01:32:42.664391	e7c5c628-0340-439b-9f2a-f72674cad332	\N	Toy14	9334	t	2	2
14	2026-07-24 01:32:50.916491	2026-07-24 01:32:50.916491	9c1cb0df-99d7-4372-ab2d-88e79511ae8f	\N	Toy12	987	t	2	2
15	2026-07-24 01:33:01.847117	2026-07-24 01:33:01.847117	a1258f62-8c62-487f-a923-702a0e6c2b52	\N	Toy14	8764	t	2	2
16	2026-07-24 01:33:08.49359	2026-07-24 01:33:08.494699	6f7cf7f3-720e-4c3d-a547-29955007b32b	\N	Toy15	8764	t	2	2
17	2026-07-24 01:33:29.713463	2026-07-24 01:33:29.713463	b9a233fc-8d69-407a-b8e4-aa2b006e1e4c	\N	Toy16	564	t	2	2
18	2026-07-24 01:33:37.104802	2026-07-24 01:33:37.104802	dcfaafc4-892e-462a-8aa1-269bea1534fc	\N	Toy18	5648	t	2	2
19	2026-07-24 01:33:44.796712	2026-07-24 01:33:44.796712	f1e9984c-0a49-4cfb-a911-b94bb4bb881a	\N	Toy19	8900	t	2	2
20	2026-07-24 01:33:55.296975	2026-07-24 01:33:55.296975	2a653e4a-a9d9-491b-b21a-8d87695ed23e	\N	Toy20	8600	t	2	2
22	2026-07-24 02:18:00.377375	2026-07-24 02:18:00.377375	202d23fe-144a-4850-908c-8fc77abc5d16	\N	Toy20	9650	t	2	2
23	2026-07-24 02:18:05.967575	2026-07-24 02:18:05.967575	6d366fb9-e419-4dad-b1d6-6f8c87d914f3	\N	Toy20	9609	t	2	2
24	2026-07-24 02:18:14.709945	2026-07-24 02:18:14.709945	ceaca8ae-2ce6-411c-ba7f-efac98513814	\N	Toy20	1200	t	2	2
25	2026-07-24 02:18:25.026706	2026-07-24 02:18:25.026706	c16e37fa-d66f-41d0-ae39-9059de94bf05	\N	Toy20	1289	t	2	2
21	2026-07-24 02:17:52.373517	2026-07-24 02:17:52.373517	34e4a524-2851-45c9-9138-4672e8b9d45f	\N	Toy20	8600	t	2	2
\.


--
-- Data for Name: sub_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sub_category (id, create_date_time, updated_date_time, uuid, sc_description, sc_name, category_id) FROM stdin;
1	2026-07-24 01:21:58.023181	2026-07-24 01:21:58.023181	db99c7a9-aeb6-44bc-af2f-34951464d0c2	\N	Camera & Photo	2
2	2026-07-24 01:23:53.857503	2026-07-24 01:23:53.857503	8ace7cd3-0420-4ee6-909a-217974ad6007	\N	Headphones	2
\.


--
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_id_seq', 2, true);


--
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 25, true);


--
-- Name: sub_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sub_category_id_seq', 2, true);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- Name: sub_category sub_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT sub_category_pkey PRIMARY KEY (id);


--
-- Name: product fk1mtsbur82frn64de7balymq9s; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fk1mtsbur82frn64de7balymq9s FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- Name: product fkd9gfnsjgfwjtaxl57udrbocsp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT fkd9gfnsjgfwjtaxl57udrbocsp FOREIGN KEY (sub_category_id) REFERENCES public.sub_category(id);


--
-- Name: sub_category fkl65dyy5me2ypoyj8ou1hnt64e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sub_category
    ADD CONSTRAINT fkl65dyy5me2ypoyj8ou1hnt64e FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- PostgreSQL database dump complete
--

